### ISSUE TITLE
Make config in CaseFormat publicly accessible

### ISSUE THREAD

**Issue by savvasdalkitsis** [pearxteam/kasechange#4]
This is related to the earlier enhancement I raised #3 

In CaseFormat, I had intentionally made the config value publicly accessible but didn't explain my reasoning behind it (my apologies):

https://github.com/pearxteam/kasechange/blob/21ea6a12a0b7fc4b2aea66e9679d10c41cdb7716/src/commonMain/kotlin/net/pearx/kasechange/CaseFormat.kt#L13

Since the API is now extensible, clients might want to mix and match predefined formats with their own and the only way to do it in a concise manner would be something like this:

```
val formats = mapOf(
    "SCREAMING_SNAKE_CASE" to CaseFormat.UPPER_UNDERSCORE.config,
    "snake_case" to CaseFormat.LOWER_UNDERSCORE.config,
    "Pascal.Dot.Case" to CaseFormatterConfig(false, ".", wordCapitalize = true, firstWordCapitalize = true)
)
```

which can then be used like so:

```
val format : String = parseFormatFromConfigurationFile()
"Some words".toCase(formats["format"] ?: throw IllegalArgumentException("Unrecognised format"))
```

If the `config` is not exposed, the only way is to keep two constructs and depending on the value you might want to use, know which construct to pull the formatter from.

Any thoughts on this?

**Comment by mrapplexz** [comment]
How about making `formats` use `CaseFormatter`s, not their configs?
```kotlin
val formats = mapOf(
    "SCREAMING_SNAKE_CASE" to CaseFormat.UPPER_UNDERSCORE,
    "snake_case" to CaseFormat.LOWER_UNDERSCORE,
    "Pascal.Dot.Case" to CaseFormatterConfigurable(CaseFormatterConfig(false, ".", wordCapitalize = true, firstWordCapitalize = true))
)
```

```kotlin
val format : String = parseFormatFromConfigurationFile()
"Some words".toCase(formats[format] ?: throw IllegalArgumentException("Unrecognised format"))
```

**Comment by savvasdalkitsis** [comment]
I blame the morning hours and not having my coffee :)

I will close this :D
